# Generated by Django 5.2.7 on 2025-12-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transaction_credit_type_alter_transaction_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('BUYER', 'Buyer (Organization)'), ('SELLER', 'Seller')], max_length=10),
        ),
    ]
